spring:
  cache:
    type: redis

  application:
    name: Mania-Place

  datasource:
    url: jdbc:mysql://localhost:3307/mania_place
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    #    hibernate.ddl-auto: create
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  mail:
    host: email-smtp.ap-northeast-2.amazonaws.com
    port: 587
    username: ${SES_USERNAME}
    password: ${SES_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret:
    key: ${SECRET_KEY}

email: ${EMAIL}