spring:
  cache:
    type: redis

  application:
    name: Mania-Place

  datasource:
    url: jdbc:mysql://localhost:3307/mania_place
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    #    hibernate.ddl-auto: create
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true

jwt:
  secret:
    key: 11231324sdafdasdfasdfasd5646456asd5f4as6d5f4a56sdf423asd1f


#뉴스피드 캐시 설정
cache:
  newsfeed:
    ttl: 300 # 300초 5분
    list-ttl: 60 # 60초 1분
