spring:
  cache:
    type: redis

  application:
    name: Mania-Place

  datasource:
    url: jdbc:mysql://localhost:3307/mania_place
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Redis 설정 추가
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  jpa:
    #    hibernate.ddl-auto: create
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true


  mail:
    host: email-smtp.ap-northeast-2.amazonaws.com
    port: 587
    username: ${SES_USERNAME}
    password: ${SES_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
email: ${EMAIL}

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    defaults:
      enabled: true

jwt:
  secret:
    key: ${SECRET_KEY}

rabbitmq:
  host: localhost
  port: 5672
  username: guest # docker-compose.yml에 설정한 user와 동일
  password: guest # docker-compose.yml에 설정한 pass와 동일



