# .github/ISSUE_TEMPLATE/chore.yml
name:  Chore
description: 기타 작업을 요청합니다
title: "[CHORE] "
labels: ["chore", "maintenance"]
body:
  - type: markdown
    attributes:
      value: |
        기타 작업(빌드, 설정, 문서 등)을 위한 템플릿입니다.
        
  - type: textarea
    id: chore-description
    attributes:
      label: 작업 설명
      description: 어떤 작업이 필요한가요?
      placeholder: 수행할 작업에 대해 설명해주세요
    validations:
      required: true
      
  - type: textarea
    id: task-list
    attributes:
      label: 작업 목록
      description: 수행해야 할 작업들을 나열해주세요
      placeholder: |
        - [ ] 작업 1
        - [ ] 작업 2
        - [ ] 작업 3
    validations:
      required: true
